version: '3.8'

services:
  mariadb:
    build: requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    # Secrets for Database
    secrets:
      - db_password
      - db_root_password
    # Environment 
    environment:
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}

  wordpress:
    build: requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/wordpress
    # Secrets for WordPress
    secrets:
      - db_password
      - credentials
      - user1_password
    # Environment 
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - SITE_TITLE=${SITE_TITLE}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_HOST=mariadb
      - USER1_LOGIN=${USER1_LOGIN}
      - USER1_EMAIL=${USER1_EMAIL}

  nginx:
    build: requirements/nginx
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/wordpress

# Secrets Definition
secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
  credentials:
    file: ./secrets/credentials.txt
  user1_password:
    file: ./secrets/user1_password.txt

# Volumes Definition
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/otmane/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/otmane/data/wordpress

networks:
  inception:
    driver: bridge