events {
    # The default for handling connections
}

http {
    include /etc/nginx/mime.types;
    
    server {
        # 1. Listen on port 443 (HTTPS) only
        listen 443 ssl;
        ssl_protocols TLSv1.2 TLSv1.3;
        
        # 2. SSL Certificate locations (generated in the Dockerfile)
        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;

        # 3. Server Name
        server_name otboumeh.42.fr;

        # 4. Root directory (where the website files live inside the container)
        root /var/www/wordpress;
        index index.php index.html index.htm;

        # 5. Handling requests
        location / {
            try_files $uri $uri/ =404;
        }

        # 6. Handling PHP files (Pass them to the WordPress container)
        location ~ \.php$ {
            include snippets/fastcgi-php.conf;
            # 'wordpress' is the name of the other container we will build later
            # '9000' is the standard port for PHP-FPM
            fastcgi_pass wordpress:9000;
        }
    }
}
