[www]
; The user that runs PHP
user = www-data
group = www-data

; LISTEN ON PORT 9000
listen = 9000

; Process management settings
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
